spring:
  application:
    name: Komek Chat API Server
  profiles:
    active: dev
  jpa:
    database: default
  security:
    user:
      name: admin
      password: qwerty
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

server:
  port: 8080
  servlet:
    context-path: /chat


komek:
  properties:
    security:
      enabled: false
      username: 'admin'
      password: 'qwerty'




