spring:
  datasource:
    # TODO
    url: "jdbc:postgresql://127.0.0.1:5432/chat?currentSchema=chat_example"
    username: "postgres"
    password: "1"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    user: postgres
    password: 1
    # TODO
    url: jdbc:postgresql://localhost:5432/chat
    schemas: chat_example
