COMMENT ON SCHEMA chat_example IS 'Main System Chat';

/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE if not exists chat_example.conv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE if not exists chat_example.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE if not exists chat_example.watching_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE if not exists chat_example.messages_read_by_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE if not exists chat_example.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

/******************** Add Table: chat_example.conv ************************/

/* Build Table Structure */
CREATE TABLE if not exists chat_example.conversation
(
    id              INTEGER DEFAULT nextval(
            'chat_example.conv_id_seq'::regclass)      NOT NULL,
    title           VARCHAR(100)          NULL,
    created_user_id INTEGER               NOT NULL,
    date_created    TIMESTAMP             NOT NULL,
    date_updated    TIMESTAMP             NOT NULL,
    is_private      BOOLEAN             default false
);
-- alter table chat_example.conversation
--     add is_private boolean default false;
/* Add Primary Key */
ALTER TABLE chat_example.conversation
    ADD constraint pkconv_id
        PRIMARY KEY (id);

/******************** Add Table: chat_example.user ************************/

/* Build Table Structure */

CREATE TABLE  if not exists chat_example.users
(
    id              INTEGER DEFAULT nextval(
    'chat_example.user_id_seq'::regclass)      NOT NULL,
    phone               CHARACTER VARYING(128)                    NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    verification_code   CHARACTER VARYING(16)                     NOT NULL,
    verification_status CHARACTER VARYING(16),
    message             CHARACTER VARYING(256)
);

/******************** Add Table: chat_example.messages ************************/

/* Build Table Structure */
CREATE TABLE if not exists chat_example.messages
(
    id                  INTEGER DEFAULT nextval(
            'chat_example.messages_id_seq'::regclass) NOT NULL,
    conversation_id     INTEGER          NOT NULL,
    reply_on_message_id INTEGER          NULL,
    messaged_user_id    INTEGER          NOT NULL,
    date_created        TIMESTAMP        NOT NULL,
    date_updated        TIMESTAMP        NOT NULL,
    message             TEXT             NOT NULL
);

/* Add Primary Key */
ALTER TABLE chat_example.messages
    ADD constraint pkmessages_id
        PRIMARY KEY (id);

/******************** Add Table: chat_example.messages_watching_users ************************/

/* Build Table Structure */
CREATE TABLE if not exists chat_example.watching_users
(
    id              INTEGER DEFAULT nextval(
            'chat_example.watching_users_id_seq'::regclass) NOT NULL,
    user_id         INTEGER                    NOT NULL,
    conversation_id INTEGER                    NOT NULL,
    date_created    TIMESTAMP                  NOT NULL,
    date_updated    TIMESTAMP                  NOT NULL
);

/* Add Primary Key */
ALTER TABLE chat_example.watching_users
    ADD CONSTRAINT pkwatching_users_id
        PRIMARY KEY (id);


/******************** Add Table: chat_example.messages_read_by_users ************************/

/* Build Table Structure */
CREATE TABLE if not exists chat_example.messages_read_by_users
(
    id              INTEGER DEFAULT nextval(
            'chat_example.messages_read_by_users_id_seq'::regclass) NOT NULL,
    read_by_user_id INTEGER                            NOT NULL,
    messages_id     INTEGER                            NOT NULL,
    conversation_id INTEGER                            NOT NULL,
    date_created    TIMESTAMP                          NOT NULL,
    date_updated    TIMESTAMP                          NOT NULL
);

/* Add Primary Key */
ALTER TABLE chat_example.messages_read_by_users
    ADD CONSTRAINT pkmessages_read_by_users_id
        PRIMARY KEY (id);

/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_messages_conv_id */
ALTER TABLE chat_example.messages
    ADD CONSTRAINT fk_messages_conv_id
        FOREIGN KEY (conversation_id) REFERENCES chat_example.conversation (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_messages_reply_on_message_id */
ALTER TABLE chat_example.messages
    ADD CONSTRAINT fk_messages_reply_on_message_id
        FOREIGN KEY (reply_on_message_id) REFERENCES chat_example.messages (id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_watching_users_conv_id */
ALTER TABLE chat_example.watching_users
    ADD CONSTRAINT fk_watching_users_conv_id
        FOREIGN KEY (conversation_id) REFERENCES chat_example.conversation (id)
            ON UPDATE NO ACTION ON DELETE CASCADE;

/* Add Foreign Key: fk_messages_read_by_users_message_id */
ALTER TABLE chat_example.messages_read_by_users
    ADD CONSTRAINT fk_messages_read_by_users_message_id
        FOREIGN KEY (messages_id) REFERENCES chat_example.messages (id)
            ON UPDATE NO ACTION ON DELETE CASCADE;

/* Add Foreign Key: fk_messages_read_by_users_conversation_id */
ALTER TABLE chat_example.messages_read_by_users
    ADD CONSTRAINT fk_messages_read_by_users_conversation_id
        FOREIGN KEY (conversation_id) REFERENCES chat_example.conversation (id)
            ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE chat_example.messages_read_by_users ADD CONSTRAINT constraint_read_by_users
    UNIQUE (read_by_user_id, messages_id, conversation_id);

